import { Layout } from "@/components/Layout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { formatTime, getBadge, getExamConfig } from "@/lib/examUtils";
import { getAllAttempts } from "@/lib/storage";
import { Link, useNavigate, useParams } from "@tanstack/react-router";
import {
  Award,
  BookOpen,
  CheckCircle2,
  ChevronRight,
  Clock,
  Download,
  Home,
  RefreshCw,
  Target,
  TrendingUp,
  XCircle,
} from "lucide-react";

const BADGE_CONFIG: Record<
  string,
  {
    emoji: string;
    headline: string;
    sub: string;
    style: string;
    isPassing: boolean;
  }
> = {
  "Top Candidate": {
    emoji: "🏆",
    headline: "Top Candidate",
    sub: "Outstanding Performance — Elite Level!",
    style: "bg-accent/15 border-accent/50 text-accent-foreground",
    isPassing: true,
  },
  "Academy Bound": {
    emoji: "🎖️",
    headline: "Academy Bound",
    sub: "You Passed! You are ready for the next step.",
    style: "bg-primary/15 border-primary/50 text-primary-foreground",
    isPassing: true,
  },
  Ready: {
    emoji: "⭐",
    headline: "Ready",
    sub: "You are Getting There — Keep Practicing!",
    style: "bg-secondary border-border text-secondary-foreground",
    isPassing: false,
  },
  Rookie: {
    emoji: "🔰",
    headline: "Rookie",
    sub: "Keep Practicing — Review Your Weak Areas.",
    style: "bg-muted border-border text-muted-foreground",
    isPassing: false,
  },
};

const MOTIVATIONAL: Record<string, string> = {
  "Top Candidate":
    "Exceptional work! You have demonstrated elite-level knowledge. Review any missed questions to sharpen your skills even further.",
  "Academy Bound":
    "Congratulations on passing! You have the skills to succeed. Continue drilling the categories where you lost points.",
  Ready:
    "You are close — just a few more points and you will cross the passing threshold. Focus on your weakest categories and retake the exam.",
  Rookie:
    "Every officer started somewhere. Study the recommended categories below and come back stronger. You have got this.",
};

function getCategoryColor(pct: number): string {
  if (pct >= 80) return "text-primary";
  if (pct >= 65) return "text-accent";
  return "text-destructive";
}

function getCategoryProgressClass(pct: number): string {
  if (pct >= 80) return "progress-gold";
  if (pct >= 65) return "[&_[role=progressbar]]:bg-accent";
  return "[&_[role=progressbar]]:bg-destructive";
}

function exportResults(attempt: ReturnType<typeof getAllAttempts>[number]) {
  const lines: string[] = [
    "==============================================",
    "           RECRUITIQ — RESULTS REPORT",
    "==============================================",
    "",
    `Exam:          ${attempt.examTitle}`,
    `Date:          ${new Date(attempt.completedAt).toLocaleString()}`,
    `Time Spent:    ${formatTime(attempt.timeSpentSeconds)}`,
    "",
    "--- SCORE ---",
    `Score:         ${attempt.score} / ${attempt.totalQuestions}`,
    `Percentage:    ${attempt.percentage}%`,
    `Result:        ${attempt.passed ? "PASSED" : "FAILED"}`,
    `Badge:         ${attempt.badge}`,
    "",
    "--- CATEGORY BREAKDOWN ---",
    ...Object.entries(attempt.categoryScores)
      .sort((a, b) => a[1].percentage - b[1].percentage)
      .map(
        ([cat, cs]) =>
          `${cat.padEnd(35)} ${cs.correct}/${cs.total}  (${cs.percentage}%)`,
      ),
    "",
    "==============================================",
    "         Generated by RecruitIQ",
    "==============================================",
  ];
  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `exam-results-${attempt.id}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function ResultsPage() {
  const { attemptId } = useParams({ from: "/results/$attemptId" });
  const navigate = useNavigate();
  const attempt = getAllAttempts().find((a) => a.id === attemptId);

  if (!attempt) {
    return (
      <Layout>
        <div
          className="text-center py-24 space-y-4"
          data-ocid="results-not-found"
        >
          <Target className="w-12 h-12 text-muted-foreground mx-auto opacity-40" />
          <p className="font-display font-semibold text-lg">
            Attempt Not Found
          </p>
          <p className="text-muted-foreground text-sm">
            This attempt may have been cleared or the link is invalid.
          </p>
          <Link to="/">
            <Button className="mt-2">Back to Home</Button>
          </Link>
        </div>
      </Layout>
    );
  }

  const config = getExamConfig(attempt.examId);
  const badge = getBadge(attempt.percentage);
  const badgeCfg = BADGE_CONFIG[badge];
  const sortedCategories = Object.entries(attempt.categoryScores).sort(
    (a, b) => a[1].percentage - b[1].percentage,
  );
  const weakCategories = sortedCategories.slice(0, 3);

  return (
    <Layout>
      {/* ─── PASS / FAIL BANNER ─────────────────────────────── */}
      <div
        className={`rounded-2xl border-2 p-6 mb-5 text-center relative overflow-hidden ${
          attempt.passed
            ? "bg-accent/10 border-accent/40"
            : "bg-destructive/10 border-destructive/30"
        }`}
        data-ocid="result-hero-banner"
      >
        <div className="text-6xl mb-3 leading-none">{badgeCfg.emoji}</div>
        <h1 className="font-display text-2xl font-bold mb-1">
          {attempt.passed ? "Congratulations!" : "Keep Training!"}
        </h1>
        <p className="text-muted-foreground text-sm mb-3">{config.title}</p>
        <div
          className={`inline-flex items-center gap-2 px-5 py-2 rounded-full border font-semibold text-sm ${badgeCfg.style}`}
        >
          <Award className="w-4 h-4" />
          {badgeCfg.headline}
        </div>
        <p className="mt-3 text-xs text-muted-foreground">{badgeCfg.sub}</p>

        {/* Pass/Fail chip */}
        <div className="absolute top-4 right-4">
          {attempt.passed ? (
            <span className="flex items-center gap-1 text-xs font-bold text-accent bg-accent/20 border border-accent/30 px-2 py-1 rounded-full">
              <CheckCircle2 className="w-3.5 h-3.5" /> PASS
            </span>
          ) : (
            <span className="flex items-center gap-1 text-xs font-bold text-destructive bg-destructive/10 border border-destructive/30 px-2 py-1 rounded-full">
              <XCircle className="w-3.5 h-3.5" /> FAIL
            </span>
          )}
        </div>
      </div>

      {/* ─── SCORE SUMMARY ─────────────────────────────────── */}
      <Card className="p-5 mb-4 border border-border" data-ocid="score-summary">
        <h2 className="font-display font-semibold text-base mb-4 flex items-center gap-2">
          <Target className="w-4 h-4 text-primary" /> Score Summary
        </h2>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-center mb-4">
          <div className="space-y-1">
            <p className="font-display text-3xl font-bold text-primary">
              {attempt.percentage}%
            </p>
            <p className="text-xs text-muted-foreground">Percentage</p>
          </div>
          <div className="space-y-1">
            <p className="font-display text-3xl font-bold">
              {attempt.score}/{attempt.totalQuestions}
            </p>
            <p className="text-xs text-muted-foreground">Correct</p>
          </div>
          <div className="space-y-1">
            <div className="flex items-center justify-center">
              {attempt.passed ? (
                <CheckCircle2 className="w-8 h-8 text-accent" />
              ) : (
                <XCircle className="w-8 h-8 text-destructive" />
              )}
            </div>
            <p
              className={`text-xs font-bold ${attempt.passed ? "text-accent" : "text-destructive"}`}
            >
              {attempt.passed ? "PASSED" : "FAILED"}
            </p>
          </div>
          <div className="space-y-1">
            <div className="flex items-center justify-center gap-1">
              <Clock className="w-5 h-5 text-muted-foreground" />
              <p className="font-display text-xl font-bold">
                {formatTime(attempt.timeSpentSeconds)}
              </p>
            </div>
            <p className="text-xs text-muted-foreground">Time Spent</p>
          </div>
        </div>
        <Progress value={attempt.percentage} className="h-3 progress-gold" />
        <div className="flex justify-between mt-1.5 text-xs text-muted-foreground">
          <span>0%</span>
          <span>Pass threshold: {config.passThreshold}%</span>
          <span>100%</span>
        </div>
      </Card>

      {/* ─── CATEGORY BREAKDOWN ────────────────────────────── */}
      <Card
        className="p-5 mb-4 border border-border"
        data-ocid="category-breakdown"
      >
        <h2 className="font-display font-semibold text-base mb-1 flex items-center gap-2">
          <TrendingUp className="w-4 h-4 text-primary" /> Category Performance
        </h2>
        <p className="text-xs text-muted-foreground mb-4">
          Sorted weakest first — focus your study where it matters most.
        </p>
        <div className="space-y-3">
          {sortedCategories.map(([cat, cs]) => (
            <div key={cat} data-ocid={`cat-row-${cat}`}>
              <div className="flex items-center justify-between text-sm mb-1">
                <span className="text-xs text-muted-foreground truncate flex-1 min-w-0 mr-2">
                  {cat}
                </span>
                <span
                  className={`text-xs font-semibold shrink-0 ${getCategoryColor(cs.percentage)}`}
                >
                  {cs.correct}/{cs.total} ({cs.percentage}%)
                </span>
              </div>
              <Progress
                value={cs.percentage}
                className={`h-2 ${getCategoryProgressClass(cs.percentage)}`}
              />
            </div>
          ))}
        </div>
      </Card>

      {/* ─── STUDY RECOMMENDATIONS ─────────────────────────── */}
      <Card
        className="p-5 mb-6 border border-border bg-muted/30"
        data-ocid="study-recommendations"
      >
        <h2 className="font-display font-semibold text-base mb-1 flex items-center gap-2">
          <BookOpen className="w-4 h-4 text-primary" /> Study Recommendations
        </h2>
        <p className="text-xs text-muted-foreground mb-3">
          {MOTIVATIONAL[badge]}
        </p>
        {weakCategories.length > 0 && (
          <>
            <p className="text-xs font-semibold text-foreground mb-2">
              Focus your study on:
            </p>
            <div className="flex flex-wrap gap-2">
              {weakCategories.map(([cat, cs]) => (
                <Badge
                  key={cat}
                  variant="outline"
                  className={`text-xs gap-1 ${getCategoryColor(cs.percentage)} border-current/30`}
                  data-ocid={`weak-cat-${cat}`}
                >
                  {cat} — {cs.percentage}%
                </Badge>
              ))}
            </div>
          </>
        )}
      </Card>

      <Separator className="my-5" />

      {/* ─── ACTION BUTTONS ─────────────────────────────────── */}
      <div
        className="grid grid-cols-1 sm:grid-cols-2 gap-3"
        data-ocid="result-actions"
      >
        <Link
          to="/review/$attemptId"
          params={{ attemptId: attempt.id }}
          className="contents"
        >
          <Button
            className="gap-2 justify-start"
            variant="default"
            data-ocid="review-answers-btn"
          >
            <BookOpen className="w-4 h-4" /> Review All Answers
          </Button>
        </Link>

        <Button
          variant="outline"
          className="gap-2 justify-start"
          data-ocid="retake-exam-btn"
          onClick={() => {
            void navigate({
              to: "/exam/$examId",
              params: { examId: String(attempt.examId) },
            });
          }}
        >
          <RefreshCw className="w-4 h-4" /> Retake This Exam
        </Button>

        <Link
          to="/history/$examId"
          params={{ examId: String(attempt.examId) }}
          className="contents"
        >
          <Button
            variant="outline"
            className="gap-2 justify-start"
            data-ocid="view-history-btn"
          >
            <ChevronRight className="w-4 h-4" /> View Attempt History
          </Button>
        </Link>

        <Button
          variant="outline"
          className="gap-2 justify-start"
          data-ocid="export-results-btn"
          onClick={() => exportResults(attempt)}
        >
          <Download className="w-4 h-4" /> Export Results
        </Button>

        <Link to="/" className="contents">
          <Button
            variant="ghost"
            className="gap-2 justify-start sm:col-span-2"
            data-ocid="back-home-btn"
          >
            <Home className="w-4 h-4" /> Go Home
          </Button>
        </Link>
      </div>
    </Layout>
  );
}
